"""Animation as string

Revision ID: 6457a5190618
Revises: 76760496b235
Create Date: 2025-05-13 11:50:54.161454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6457a5190618'
down_revision = '76760496b235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('animation',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('animation',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
