"""Replace status with on and online fields

Revision ID: 76760496b235
Revises: 
Create Date: 2025-05-08 14:25:36.793091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76760496b235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('online')
        batch_op.drop_column('on')

    # ### end Alembic commands ###
