services:

  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    networks:
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 443:443
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

networks:
  frontnet: