services:

  backend:
    build: .
    command: >
      sh -c "flask db init && flask db migrate && flask db upgrade && flask run --host=0.0.0.0"
    restart: always
    ports:
      - 5000:5000
    networks:
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 443:443
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

networks:
  frontnet: