services:

  backend:
    build: .
    restart: always
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - frontnet

  proxy:
    build: proxy
    restart: always
    ports:
      - 443:443
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

networks:
  frontnet: